### ISSUE TITLE
problem?

### ISSUE THREAD

**Issue by FrankPortman** [APTy/gibs#1]
hi excuse me i thought this was a Gibbs sampler but when i ran it i didn't get any posterior distributions back how do i uninstall?

**Comment by APTy** [comment]
Thanks @FrankPortman, this [SO post](http://stackoverflow.com/questions/13792254/removing-packages-installed-with-go-get) has good steps for uninstalling Go packages. Alternatively, you can find a Gibbs sampler [here](https://github.com/wpm/Naive-Bayes-Gibbs-Sampler).
